blank_issues_enabled: false
contact_links:
  - name: Roadmap & status updates
    url: https://github.com/UnwrappedDesign/oxbow/discussions
    about: Follow along and share feedback as we prepare the new design system.
  - name: Community guidelines
    url: https://github.com/UnwrappedDesign/oxbow/blob/main/COMMUNITY_RULES.md
    about: Please review before opening an issue.
